export default{
    scanQr:'/SC_ncm/scanQr',
    saveSCYzm:'/SC_ncm/saveSCYzm',
    bindingQr:'/SC_ncm/bindingQr',
	querySCUserByPhone:'/SC_ncm/querySCCarOwnerByPhone',
	saveSCMessage:'/SC_ncm/saveSCMessage',
    sendMessage:'/SC_ncm/sendMessage',
    checkLicensePlate:'/SC_ncm/checkLicensePlate',
    updateBindingQr:'/SC_ncm/updateBindingQr',
	queryKpAd:'/SC_ncm/queryKpAd',
    checkLogin:'/SC_ncm/checkLogin',
    querySCCarOwner:"/SC_ncm/querySCCarOwner",//查车主信息
    queryLicensePlate:"/SC_ncm/queryLicensePlate",
    saveSCTyreWarranty:"/SC_ncm/saveSCTyreWarranty",
    saveSCZBYzm:"/SC_ncm/saveSCZBYzm",
    storeUserLogin:"/SC_ncm/storeUserLogin",
	queryCGMenuByPhone:"/SC_ncm/queryCGMenuByPhone",
	saveCGUser:"/SC_ncm/saveCGUser",
}
